Repository Moe1177/SOEN341_Winter2025, pull requests merged in 2025-04, with the labels that each got.

#123 Fix chatbot connection issue bug (#120, #121)
  chatbot-backend/.dockerignore
  chatbot-backend/.gitignore
  chatbot-backend/Dockerfile
  chatbot-backend/app.py
  chatbot-backend/requirements.txt
  soen341-frontend/Components/ui/chatbot-dialog.tsx
Labels: bug

#127 Allow users to send and download attachements in group, and direct messages (#126 & #127)
  .vscode/settings.json
  soen341-backend/pom.xml
  soen341-backend/src/main/java/com/example/soen341_backend/config/GridFSConfig.java
  soen341-backend/src/main/java/com/example/soen341_backend/config/MultipartConfig.java
  soen341-backend/src/main/java/com/example/soen341_backend/message/FileService.java
  soen341-backend/src/main/java/com/example/soen341_backend/message/Message.java
  soen341-backend/src/main/java/com/example/soen341_backend/message/MessageController.java
  soen341-backend/src/main/java/com/example/soen341_backend/message/MessageService.java
  soen341-backend/src/main/java/com/example/soen341_backend/payload/WebSocketMessage.java
  soen341-backend/src/main/java/com/example/soen341_backend/security/JwtAuthFilter.java
  soen341-backend/src/main/java/com/example/soen341_backend/security/SecurityConfig.java
  soen341-frontend/app/chat/components/message-input.tsx
  soen341-frontend/app/chat/components/message-item.tsx
  soen341-frontend/app/chat/components/messaging.tsx
  soen341-frontend/hooks/useToken.ts
  soen341-frontend/lib/types.ts
Labels: user story

#133 Critical diagram update (#131)
  BlockDiagram_SOEN341_Winter2025.png
Labels: documentation

#134 Added naming conventions for clarity (#131)
  README.md
Labels: documentation
