Repository Moe1177/SOEN341_Winter2025, pull requests merged in 2025-03, with the labels that each got.

#71 Make group and direct messaging work by displaying the messages directly without needing to refresh (#70)
  soen341-backend/Dockerfile
  soen341-backend/pom.xml
  soen341-backend/src/main/java/com/example/soen341_backend/channel/Channel.java
  soen341-backend/src/main/java/com/example/soen341_backend/channel/ChannelController.java
  soen341-backend/src/main/java/com/example/soen341_backend/channel/ChannelRepository.java
  soen341-backend/src/main/java/com/example/soen341_backend/channel/ChannelService.java
  soen341-backend/src/main/java/com/example/soen341_backend/config/WebSocketConfig.java
  soen341-backend/src/main/java/com/example/soen341_backend/message/MessageController.java
  soen341-backend/src/main/java/com/example/soen341_backend/message/MessageService.java
  soen341-backend/src/main/java/com/example/soen341_backend/payload/WebSocketController.java
  soen341-backend/src/main/java/com/example/soen341_backend/security/SecurityConfig.java
  soen341-backend/src/main/java/com/example/soen341_backend/user/UserController.java
Labels: 5

#69 CI/CD tests implementation
  .github/workflows/ci-pipeline.yml
  soen341-backend/src/main/resources/application.properties
  soen341-frontend/Components/AuroraBackgroundDemo.tsx
  soen341-frontend/Components/Features.tsx
  soen341-frontend/Components/MessageInterface.tsx
  soen341-frontend/Components/MessagingFooter.tsx
  soen341-frontend/Components/Navbar.tsx
  soen341-frontend/Components/ThreeDCardDemo.tsx
  soen341-frontend/Components/footer.tsx
  soen341-frontend/Components/sidemenu.tsx
  soen341-frontend/Components/signup-form-demo.tsx
  soen341-frontend/Components/ui/input.tsx
  soen341-frontend/app/Login/page.tsx
  soen341-frontend/app/layout.tsx
  soen341-frontend/app/page.tsx
  soen341-frontend/package-lock.json
Labels: 2

#75 Integrate the chatting interface with the most of the backend functionalities (channels, messaging) #74
  soen341-backend/src/main/java/com/example/soen341_backend/channel/Channel.java
  soen341-backend/src/main/java/com/example/soen341_backend/channel/ChannelService.java
  soen341-backend/src/main/java/com/example/soen341_backend/message/MessageService.java
  soen341-backend/src/main/java/com/example/soen341_backend/user/UserService.java
  soen341-frontend/Components/DirectMessagesList.tsx
  soen341-frontend/Components/Navbar.tsx
  soen341-frontend/Components/SignUp.tsx
  soen341-frontend/Components/channel-invite-dialog.tsx
  soen341-frontend/Components/conversation-header.tsx
  soen341-frontend/Components/create-channel-dialog.tsx
  soen341-frontend/Components/create-direct-message-dialog.tsx
  soen341-frontend/Components/message-input.tsx
  soen341-frontend/Components/message-list.tsx
  soen341-frontend/Components/messaging.tsx
  soen341-frontend/Components/sidebar.tsx
  soen341-frontend/Components/signup-form-demo.tsx
  soen341-frontend/Components/ui/alert.tsx
  soen341-frontend/Components/ui/avatar.tsx
  soen341-frontend/Components/ui/button.tsx
  soen341-frontend/Components/ui/dialog.tsx
  soen341-frontend/Components/ui/input copy.tsx
  soen341-frontend/Components/ui/label copy.tsx
  soen341-frontend/Components/ui/scroll-area.tsx
  soen341-frontend/Components/ui/textarea.tsx
  soen341-frontend/app/Login/page.tsx
  soen341-frontend/app/chat/page.tsx
  soen341-frontend/app/direct-messaging/page.tsx
  soen341-frontend/app/layout.tsx
  soen341-frontend/lib/types.ts
  soen341-frontend/lib/use-websocket.ts
  soen341-frontend/package-lock.json
  soen341-frontend/package.json
Labels: development, 13

#76 Block Architecture Appended (#77)
  BlockDiagram_SOEN341_Winter2025.png
  README.md
Labels: 1

#89 Display members for each group channel with the ability to promote members to admins & also major Chat UI update (#85, #86, #88)
  .github/workflows/ci-pipeline.yml
  README.md
  soen341-backend/src/main/java/com/example/soen341_backend/channel/ChannelController.java
  soen341-backend/src/main/java/com/example/soen341_backend/channel/ChannelService.java
  soen341-backend/src/main/java/com/example/soen341_backend/message/Message.java
  soen341-backend/src/main/java/com/example/soen341_backend/message/MessageController.java
  soen341-backend/src/main/java/com/example/soen341_backend/message/MessageService.java
  soen341-backend/src/main/java/com/example/soen341_backend/payload/WebSocketController.java
  soen341-backend/src/main/java/com/example/soen341_backend/payload/WebSocketMessage.java
  soen341-backend/src/main/java/com/example/soen341_backend/user/UserController.java
  soen341-backend/src/main/java/com/example/soen341_backend/user/UserRepository.java
  soen341-backend/src/main/java/com/example/soen341_backend/user/UserService.java
  soen341-frontend/Components/channel-members-list.tsx
  soen341-frontend/Components/conversation-header.tsx
  soen341-frontend/Components/create-direct-message-dialog.tsx
  soen341-frontend/Components/message-input.tsx
  soen341-frontend/Components/message-list.tsx
  soen341-frontend/Components/messaging.tsx
  soen341-frontend/Components/sidebar.tsx
  soen341-frontend/Components/ui/alert-dialog.tsx
  soen341-frontend/Components/ui/confirm-dialog.tsx
  soen341-frontend/Components/ui/tooltip.tsx
  soen341-frontend/app/globals.css
  soen341-frontend/app/layout.tsx
  soen341-frontend/hooks/useAuth.ts
  soen341-frontend/hooks/useChannels.ts
  soen341-frontend/hooks/useDirectMessages.ts
  soen341-frontend/hooks/useMessaging.ts
  soen341-frontend/lib/use-websocket.ts
  soen341-frontend/lib/utils.ts
  soen341-frontend/next.config.ts
  soen341-frontend/package-lock.json
  soen341-frontend/package.json
  soen341-frontend/tailwind.config.ts
Labels: user story, 2

#92 Fix issues when deploying frontend caused by backend origin restrictions (#90, #91)
  README.md
  soen341-backend/src/main/java/com/example/soen341_backend/config/WebSocketConfig.java
  soen341-backend/src/main/java/com/example/soen341_backend/security/SecurityConfig.java
  soen341-frontend/Components/auth/SigninForm.tsx
  soen341-frontend/Components/client-only.tsx
  soen341-frontend/app/chat/page.tsx
  soen341-frontend/hooks/useAuth.ts
Labels: bug, development, 1

#97 Fix bugs with recipient username not being correctly shown as well as admins not being processed properly (#95, #96)
  soen341-backend/src/main/java/com/example/soen341_backend/channel/Channel.java
  soen341-backend/src/main/java/com/example/soen341_backend/channel/ChannelService.java
  soen341-frontend/Components/channel-invite-dialog.tsx
  soen341-frontend/Components/channel-members-list.tsx
  soen341-frontend/Components/messaging.tsx
  soen341-frontend/app/layout.tsx
  soen341-frontend/hooks/useChannels.ts
  soen341-frontend/hooks/useConversations.ts
  soen341-frontend/lib/types.ts
  soen341-frontend/package-lock.json
  soen341-frontend/package.json
Labels: bug, 2

#105 Refactored frontend directory and added important UI/UX improvements
  soen341-frontend/Components/auth/SigninForm.tsx
  soen341-frontend/Components/auth/SignupForm.tsx
  soen341-frontend/Components/auth/VerificationForm.tsx
  soen341-frontend/Components/ui/LoadingOverlay.tsx
  soen341-frontend/app/chat/components/channel-invite-dialog.tsx
  soen341-frontend/app/chat/components/channel-members-list.tsx
  soen341-frontend/app/chat/components/conversation-header.tsx
  soen341-frontend/app/chat/components/create-channel-dialog.tsx
  soen341-frontend/app/chat/components/create-direct-message-dialog.tsx
  soen341-frontend/app/chat/components/join-channel-dialog.tsx
  soen341-frontend/app/chat/components/message-input.tsx
  soen341-frontend/app/chat/components/message-item.tsx
  soen341-frontend/app/chat/components/message-list.tsx
  soen341-frontend/app/chat/components/messaging.tsx
  soen341-frontend/app/chat/components/sidebar.tsx
  soen341-frontend/app/chat/page.tsx
  soen341-frontend/app/login/page.tsx
  soen341-frontend/app/page.tsx
  soen341-frontend/hooks/useAuth.ts
  soen341-frontend/hooks/useChannels.ts
  soen341-frontend/hooks/useDirectMessages.ts
  soen341-frontend/hooks/useLogout.ts
  soen341-frontend/lib/routeProtection.ts
Labels: task

#111 improve UX by adding a loader when logging and improving route security
  soen341-frontend/app/chat/components/sidebar.tsx
  soen341-frontend/lib/routeProtection.ts
Labels: task
